version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bookstore}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bookstorepwd}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fkarboul@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpwd
    ports:
      - "5050:80"
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
  pgadmin_data:
###< doctrine/doctrine-bundle ###
